# Generated by Django 4.2.28 on 2026-05-07 23:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_instructor", models.BooleanField(default=False)),
                (
                    "is_approved",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="الأدمن يوافق على المدرس قبل ما يقدر ينشر",
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/students/"
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{9,15}$"
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"is_instructor": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/instructors/"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("dr", "دكتور"),
                            ("prof", "أستاذ دكتور"),
                            ("eng", "مهندس"),
                            ("mr", "أستاذ"),
                        ],
                        default="dr",
                        max_length=10,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=2000)),
                ("expertise", models.CharField(blank=True, max_length=200)),
                ("department", models.CharField(blank=True, max_length=200)),
                ("university", models.CharField(blank=True, max_length=200)),
                (
                    "cv_file",
                    models.FileField(
                        blank=True, null=True, upload_to="instructors/cvs/"
                    ),
                ),
                ("linkedin", models.URLField(blank=True)),
                ("google_scholar", models.URLField(blank=True)),
                ("research_gate", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("total_students", models.PositiveIntegerField(default=0)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{9,15}$"
                            )
                        ],
                    ),
                ),
                ("office_hours", models.CharField(blank=True, max_length=200)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("show_cv", models.BooleanField(default=True)),
                ("show_contact", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"is_instructor": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "instructor_profiles",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
