# Generated by Django 4.2.28 on 2026-06-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="magic_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="One-time login token بيتبعت للمدرس بعد الموافقة",
                max_length=100,
            ),
        ),
    ]
