# Generated by Django 4.2.28 on 2026-05-07 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FocusSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_watch_seconds", models.PositiveIntegerField(default=0)),
                ("distracted_count", models.PositiveIntegerField(default=0)),
                (
                    "distracted_times",
                    models.JSONField(
                        blank=True, default=list, help_text="قائمة بأوقات وأسباب الشرود"
                    ),
                ),
                (
                    "focus_score",
                    models.PositiveIntegerField(
                        default=100, help_text="نسبة التركيز 0-100"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_sessions",
                        to="courses.lecture",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "focus_sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
