# Generated by Django 4.2.28 on 2026-02-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="is_free_preview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lecture",
            name="s3_key",
            field=models.CharField(
                blank=True,
                help_text="S3 object key set after direct upload from the frontend",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="video_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Admin Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                help_text="Admin must approve before the lecture is visible to students",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="video_type",
            field=models.CharField(
                choices=[
                    ("upload", "Uploaded to S3"),
                    ("youtube", "YouTube Link"),
                    ("vimeo", "Vimeo Link"),
                ],
                db_index=True,
                default="upload",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube or Vimeo URL (leave blank when uploading to S3)",
            ),
        ),
    ]
