# Generated by Django 4.2.28 on 2026-02-25 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_lecture_is_free_preview_lecture_s3_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="سعر بعد التخفيض – اتركه فارغاً لو مفيش تخفيض",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="s3_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="video_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="video_type",
            field=models.CharField(
                choices=[("upload", "S3"), ("youtube", "YouTube"), ("vimeo", "Vimeo")],
                db_index=True,
                default="upload",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="video_url",
            field=models.URLField(blank=True),
        ),
    ]
