# Generated by Django 4.2.28 on 2026-05-07 23:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="شرح مختصر لمحتوى التجربة وما سيتعلمه الطالب",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "instructor_cut",
                    models.DecimalField(
                        decimal_places=2,
                        default=70.0,
                        help_text="نسبة المدرس % (مثال: 70)",
                        max_digits=5,
                    ),
                ),
                (
                    "college_cut",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        help_text="نسبة الكلية/المنصة % (مثال: 30)",
                        max_digits=5,
                    ),
                ),
                (
                    "preview_video_url",
                    models.URLField(
                        blank=True, help_text="رابط فيديو preview مجاني (اختياري)"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="experiences/thumbnails/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("published", "منشور"),
                            ("archived", "مؤرشف"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("total_buyers", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="courses.section",
                    ),
                ),
            ],
            options={
                "db_table": "section_experiences",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SectionExperiencePurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "instructor_earn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "college_earn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المعالجة"),
                            ("completed", "مكتمل"),
                            ("failed", "فشل"),
                            ("refunded", "مُسترد"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="payments.sectionexperience",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_instructor": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "section_experience_purchases",
                "ordering": ["-purchased_at"],
                "unique_together": {("student", "experience")},
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_instructor": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
                "ordering": ["-enrolled_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "enrolled_at"],
                        name="enrollments_student_17412a_idx",
                    ),
                    models.Index(
                        fields=["course", "enrolled_at"],
                        name="enrollments_course__06db47_idx",
                    ),
                ],
                "unique_together": {("student", "course")},
            },
        ),
    ]
