# Generated by Django 4.2.28 on 2026-05-07 23:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="experiences/images/"
                    ),
                ),
                (
                    "preview_video_url",
                    models.URLField(
                        blank=True, help_text="فيديو مجاني — يشوفه الكل", null=True
                    ),
                ),
                (
                    "content_video_url",
                    models.URLField(
                        blank=True, help_text="الفيديو الكامل — للمشترين فقط", null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="اتركه فارغاً لو مفيش خصم",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("instructor_cut", models.PositiveIntegerField(default=70)),
                ("college_cut", models.PositiveIntegerField(default=30)),
                ("is_approved", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "مسودة"), ("published", "منشور")],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("total_buyers", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        limit_choices_to={"is_instructor": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_experiences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="experiences",
                        to="courses.section",
                    ),
                ),
            ],
            options={
                "db_table": "experiences",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExperiencePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "instructor_earn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "college_earn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="experiences.experience",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "experience_purchases",
                "ordering": ["-purchased_at"],
                "unique_together": {("student", "experience")},
            },
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["is_approved", "status"], name="experiences_is_appr_f89125_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["instructor", "is_approved"],
                name="experiences_instruc_a03dcf_idx",
            ),
        ),
    ]
